# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.5.5'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/google/keep-sorted
    rev: v0.4.0
    hooks:
      - id: keep-sorted

  - repo: https://github.com/jlebar/pre-commit-hooks
    rev: 62ca83ba4958da48ea44d9f24cd0aa58633376c7
    hooks:
      - id: do-not-submit
